server:
  port: 9090

spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/shareitdb
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.jdbc.bind: TRACE